### PR TITLE
updated to v0.6 API changes

### PR DESCRIPTION
**Pull request by phdsg**
as per https://github.com/VCVRack/community/issues/269

### CODE REVIEW

**Comment by cschol** [comment]
We are moving plugins migrated to v0.6 over to the new community repository structure to prepare for the Rack v0.6 release. Any chance this PR can be merged for this upcoming release? Thanks!

**Comment by cschol** [comment]
Also, the `VERSION` in the `Makefile` needs to be updated to `0.6.0`.

**Comment by phdsg** [comment]
working on updates for the PR today

**Comment by phdsg** [comment]
done. a few warnings left, but nothing related to API changes, i think.

**Comment by phdsg** [comment]
i'll post 0.6 binaries over here: https://github.com/phdsg/qwelk/issues/1

**Pull request merged**
